pipeline {
    agent any
    stages {
        stage('Checkout') {
            steps {
                checkout scm
            }
        }
        stage('Build') {
            steps {
                sh 'gradle build'
            }
        }
        //stage('Test') {
          //  steps {
            //    sh 'gradle test'
       //     }
       // }
       // stage('Deploy') {
         //   steps {
                // Add deployment steps here (e.g., deploy to a server)
           // }
       // }
    }
}
